### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f680' in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by cooldeaaap1** [severian42/GraphRAG-Local-UI#66]
The project I am running locally has encountered an error. It seems that there is an error in the file format, but the file I uploaded is indeed encoded in UTF-8, and the YAML file and input txt file are also encoded in UTF-8. What is the problem? My machine runs on Windows 11, with LLM model Llama3.1 and embedding model nomic-embedded text: latest. Both models are run locally using OLLAMA
![微信图片_20240728035021](https://github.com/user-attachments/assets/227e4438-c916-4bff-a2e0-41d9eb696a78)
![微信图片_20240728035027](https://github.com/user-attachments/assets/ff2d27ba-964f-46db-9d46-e7354c7b6b6a)
![微信图片_20240728035032](https://github.com/user-attachments/assets/1e892e44-f0ad-4e20-b8fe-ed688d8f71e5)
![微信图片_20240728035110](https://github.com/user-attachments/assets/dfef20d8-1452-4c62-915c-db316247f118)

**Comment by lovexujia** [comment]
This problem is caused by the project coding, so just adjust the project coding, or specify utf-8 as the installed python environment.

**Comment by nbdongdong** [comment]
I had a similar problem, how was this problem solved

**Comment by delbern310** [comment]
I have the same problem ,but my python environment encoding is utf-8 ,how can I solved?

**Comment by NasonZ** [comment]
Also using Windows (10). Was having the same errors but I managed to fix them. 


These issues are related to character encoding, I suspect windows terminal can't display certain characters which Mac can. 

## Issue 1: UnicodeEncodeError with Emoji Characters

### Error Message:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 0: character maps to <undefined>
```

### Explanation:
This error occurs because the Windows console is using a limited character encoding (cp1252) that doesn't support emoji characters.

### Solution:

1. Locate the file `graphrag/graphrag/index/progress/rich.py`.
2. Find the `success` method in the `RichProgressReporter` class.
3. Replace the line:
   ```python
   self._console.print(f"🚀 [green]{message}[/green]")
   ```
   with:
   ```python
   self._console.print(f"[green]SUCCESS: {message}[/green]")
   ```
   4. Repeat for all emojis in `rich.py`


## Issue 2: UnicodeDecodeError when Reading Prompt Files

### Error Message:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2386: character maps to <undefined>
```

### Explanation:
This error occurs when trying to read a text file (like a prompt file) that contains characters not supported by the default Windows encoding.

### Solution:

1. Locate the file `graphrag/graphrag/config/models/entity_extraction_config.py`.
2. Find the `resolved_strategy` method in the `EntityExtractionConfig` class.
3. Update the method as follows:

```python
def resolved_strategy(self, root_dir: str, encoding_model: str) -> dict:
    """Get the resolved entity extraction strategy."""
    from graphrag.index.verbs.entities.extraction import ExtractEntityStrategyType

    extraction_prompt = None
    if self.prompt:
        prompt_path = Path(root_dir) / self.prompt
        try:
            extraction_prompt = prompt_path.read_text(encoding='utf-8')
        except FileNotFoundError:
            print(f"Warning: Prompt file not found at {prompt_path}")
        except PermissionError:
            print(f"Warning: Permission denied when trying to read {prompt_path}")
        except UnicodeDecodeError:
            print(f"Warning: Unable to decode {prompt_path} using UTF-8 encoding")

    return self.strategy or {
        "type": ExtractEntityStrategyType.graph_intelligence,
        "llm": self.llm.model_dump(),
        **self.parallelization.model_dump(),
        "extraction_prompt": extraction_prompt,
        "max_gleanings": self.max_gleanings,
        "encoding_name": encoding_model,
        "prechunked": True,
    }
```

This change ensures that the prompt file is read using UTF-8 encoding and handles potential errors .
